title: "Yue Wu"
description: "Theoretical chemist doing path integral molecular dynamics. Sharing Cambridge natural sciences and mathematics notes"

url: "https://slepton-wu.github.io"
baseurl: ""
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  nav_links:
    - { title: "Home", url: "/" }
    - { title: "Notes", url: "/Notes/" }

collections:
  notes:
    output: true
defaults:
  - scope: { path: "", type: notes }
    values: { layout: page, permalink: /notes/:title/ }
